// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceAutoLicenta.Data;

#nullable disable

namespace ServiceAutoLicenta.Migrations
{
    [DbContext(typeof(ServiceAutoLicentaContext))]
    [Migration("20260324211017_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Client", b=>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresa")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Cnp")
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("Cnp")
                        .IsUnique()
                        .HasFilter("[Cnp] IS NOT NULL");

                    b.ToTable("Clienti");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 3, 24, 23, 10, 16, 278, DateTimeKind.Local).AddTicks(1641),
                            Email = "ion.banea@email.ro",
                            Nume = "Banea",
                            Prenume = "Ion",
                            Telefon = "0722111222"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 3, 24, 23, 10, 16, 278, DateTimeKind.Local).AddTicks(1696),
                            Email = "cristi.nicula1@email.ro",
                            Nume = "Nicula",
                            Prenume = "Cristian",
                            Telefon = "0733222333"
                        });
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Factura", b=>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEmitere")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataScadenta")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetodaPlata")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProgramareId")
                        .HasColumnType("int");

                    b.Property<string>("SerieNumar")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("StatusPlata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Subtotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TvaValoare")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("ProgramareId")
                        .IsUnique();

                    b.HasIndex("SerieNumar")
                        .IsUnique();

                    b.ToTable("Facturi");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Lucrare", b=>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Descriere")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DurataOre")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("Manopera")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("ProgramareId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProgramareId");

                    b.ToTable("Lucrari");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.LucrarePiesa", b=>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Cantitate")
                        .HasColumnType("int");

                    b.Property<int>("LucrareId")
                        .HasColumnType("int");

                    b.Property<int>("PiesaId")
                        .HasColumnType("int");

                    b.Property<decimal>("PretUnitar")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("LucrareId");

                    b.HasIndex("PiesaId");

                    b.ToTable("LucrarePiese");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Masina", b=>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AnFabricatie")
                        .HasColumnType("int");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("KmActuali")
                        .HasColumnType("int");

                    b.Property<string>("Marca")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("NrInmatriculare")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Vin")
                        .HasMaxLength(17)
                        .HasColumnType("nvarchar(17)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("NrInmatriculare")
                        .IsUnique();

                    b.HasIndex("Vin")
                        .IsUnique()
                        .HasFilter("[Vin] IS NOT NULL");

                    b.ToTable("Masini");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Piesa", b=>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodPiesa")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("PretAchizitie")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("PretVanzare")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Producator")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("StocCurent")
                        .HasColumnType("int");

                    b.Property<int>("StocMinim")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CodPiesa")
                        .IsUnique();

                    b.ToTable("Piese");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CodPiesa = "FIL-001",
                            CreatedAt = new DateTime(2026, 3, 24, 23, 10, 16, 278, DateTimeKind.Local).AddTicks(1903),
                            Denumire = "Filtru ulei Dacia Logan",
                            PretAchizitie = 18.50m,
                            PretVanzare = 35.00m,
                            Producator = "Mann Filter",
                            StocCurent = 10,
                            StocMinim = 3
                        },
                        new
                        {
                            Id = 2,
                            CodPiesa = "PLQ-002",
                            CreatedAt = new DateTime(2026, 3, 24, 23, 10, 16, 278, DateTimeKind.Local).AddTicks(1913),
                            Denumire = "Set placute frana fata VW Golf",
                            PretAchizitie = 65.00m,
                            PretVanzare = 120.00m,
                            Producator = "Bosch",
                            StocCurent = 4,
                            StocMinim = 2
                        },
                        new
                        {
                            Id = 3,
                            CodPiesa = "ULI-003",
                            CreatedAt = new DateTime(2026, 3, 24, 23, 10, 16, 278, DateTimeKind.Local).AddTicks(1918),
                            Denumire = "Ulei motor 5W40 4L",
                            PretAchizitie = 55.00m,
                            PretVanzare = 89.00m,
                            Producator = "Castrol",
                            StocCurent = 15,
                            StocMinim = 5
                        });
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Programare", b=>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataIesire")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataIntrare")
                        .HasColumnType("datetime2");

                    b.Property<int>("MasinaId")
                        .HasColumnType("int");

                    b.Property<string>("Observatii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalCuTva")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("TotalFaraTva")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Tva")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("Id");

                    b.HasIndex("MasinaId");

                    b.ToTable("Programari");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Factura", b=>
                {
                    b.HasOne("ServiceAutoLicenta.Models.Entities.Programare", "Programare")
                        .WithOne("Factura")
                        .HasForeignKey("ServiceAutoLicenta.Models.Entities.Factura", "ProgramareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programare");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Lucrare", b=>
                {
                    b.HasOne("ServiceAutoLicenta.Models.Entities.Programare", "Programare")
                        .WithMany("Lucrari")
                        .HasForeignKey("ProgramareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programare");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.LucrarePiesa", b=>
                {
                    b.HasOne("ServiceAutoLicenta.Models.Entities.Lucrare", "Lucrare")
                        .WithMany("LucrarePiese")
                        .HasForeignKey("LucrareId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceAutoLicenta.Models.Entities.Piesa", "Piesa")
                        .WithMany("LucrarePiese")
                        .HasForeignKey("PiesaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lucrare");

                    b.Navigation("Piesa");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Masina", b=>
                {
                    b.HasOne("ServiceAutoLicenta.Models.Entities.Client", "Client")
                        .WithMany("Masini")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Programare", b=>
                {
                    b.HasOne("ServiceAutoLicenta.Models.Entities.Masina", "Masina")
                        .WithMany("Programari")
                        .HasForeignKey("MasinaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Masina");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Client", b=>
                {
                    b.Navigation("Masini");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Lucrare", b=>
                {
                    b.Navigation("LucrarePiese");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Masina", b=>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Piesa", b=>
                {
                    b.Navigation("LucrarePiese");
                });

            modelBuilder.Entity("ServiceAutoLicenta.Models.Entities.Programare", b=>
                {
                    b.Navigation("Factura");

                    b.Navigation("Lucrari");
                });
#pragma warning restore 612, 618
        }
    }
}
